# Change these first
owner: Tunnelsats # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: de1.tunnelsats.com
    url: https://de1.tunnelsats.com
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: de2.tunnelsats.com
    url: https://de2.tunnelsats.com
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: de3.tunnelsats.com
    url: https://de3.tunnelsats.com
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: br1.tunnelsats.com
    url: https://br1.tunnelsats.com
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: us1.tunnelsats.com
    url: https://us1.tunnelsats.com
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: sg1.tunnelsats.com
    url: https://sg1.tunnelsats.com
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Tunnel⚡️Sats Frontend
    url: https://tunnelsats.com
    expectedStatusCodes:
      - 200
      - 201
      - 404

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tunnelsats.com
  #baseUrl: /upptime
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://github.com/Tunnelsats/upptime/raw/master/assets/tunnelsats_banner_640_320.png
  name: Tunnel⚡️Sats Status
  introTitle: "Tunnel⚡️Sats Server Status"
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Homepage
      href: https://tunnelsats.com
    - title: Status
      href: https://status.tunnelsats.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Telegram
      href: https://t.me/+NJylaUom-rxjYjU6

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
  
i18n:
  footer: Canary Warrent Notification: Tunnel⚡️Sats has received 0 (Zero) government requests for information. <br /> This page is powered by [Upptime](https://upptime.js.org)
  
